### ISSUE TITLE
[Crash]: Crash Report: Minecraft 1.20.1 - IllegalArgumentException in Ars Nouveau Loot Generation Causing Botania Loonium Block Entity Crash

### ISSUE THREAD

**Issue by Alartias** [AllTheMods/All-the-mods-9-Sky#159]
### Possible Fixes

Yes

### Modpack Version

1.0.1

### What happened?

*My english is not good so this issue is written by ChatGPT.
Here's the crash issue report in English:

---

### Minecraft Crash Issue Report

**Time:** 2024-06-07 11:42:30  
**Description:** Ticking block entity  
**Error:** `java.lang.IllegalArgumentException: bound must be positive`

#### Detailed Error Analysis

The crash occurs due to an illegal argument being passed to the `java.util.Random.nextInt` method, which requires a positive bound. The offending call is made with a non-positive integer (likely zero or negative), causing an `IllegalArgumentException`.

**Error Stack Trace:**
```java
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:322) ~[?:?] {re:mixin}
    at com.hollingsworth.arsnouveau.api.loot.DungeonLootTables.lambda$static$17(DungeonLootTables.java:66) ~[ars_nouveau-1.20.1-4.11.0-all.jar%23467!/:4.11.0] {re:classloading}
    at com.hollingsworth.arsnouveau.api.loot.DungeonLootTables.getRandomItem(DungeonLootTables.java:76) ~[ars_nouveau-1.20.1-4.11.0-all.jar%23467!/:4.11.0] {re:classloading}
    at com.hollingsworth.arsnouveau.api.loot.DungeonLootTables.getRandomRoll(DungeonLootTables.java:89) ~[ars_nouveau-1.20.1-4.11.0-all.jar%23467!/:4.11.0] {re:classloading}
    at com.hollingsworth.arsnouveau.api.loot.DungeonLootEnhancerModifier.doApply(DungeonLootEnhancerModifier.java:50) ~[ars_nouveau-1.20.1-4.11.0-all.jar%23467!/:4.11.0] {re:classloading}
    at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.2.20-universal.jar%23727!/:?] {re:classloading}
    at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1186) ~[forge-1.20.1-47.2.20-universal.jar%23727!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.hammerlib.json:ForgeHooksMixin,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:A}
    at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LootTableAccessor,pl:mixin:APP:balm.mixins.json:LootTableMixin,pl:mixin:APP:botania_xplat.mixins.json:LootTableMixin,pl:mixin:APP:tombstone.mixins.json:accessor.LootTableAccessor,pl:mixin:APP:croptopia.mixins.json:LootTableAccessor,pl:mixin:A}
    at net.minecraft.world.level.storage.loot.LootTable.m_287195_(LootTable.java:112) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LootTableAccessor,pl:mixin:APP:balm.mixins.json:LootTableMixin,pl:mixin:APP:botania_xplat.mixins.json:LootTableMixin,pl:mixin:APP:tombstone.mixins.json:accessor.LootTableAccessor,pl:mixin:APP:croptopia.mixins.json:LootTableAccessor,pl:mixin:A}
    at vazkii.botania.common.block.flower.functional.LooniumBlockEntity.tickFlower(LooniumBlockEntity.java:82) ~[Botania-1.20.1-444-FORGE.jar%23477!/:1.20.1-444-FORGE] {re:classloading}
    at vazkii.botania.api.block_entity.SpecialFlowerBlockEntity.commonTick(SpecialFlowerBlockEntity.java:99) ~[Botania-1.20.1-444-FORGE.jar%23477!/:1.20.1-444-FORGE] {re:classloading,re:mixin}
    at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.world_border.BoundTickingBlockEntityMixin,pl:mixin:A}
    at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.RebindableTickingBlockEntityWrapperAccessor,pl:mixin:A}
    at net.minecraft.world.level.Level.redirect$dhh000$observable$redirectTick(Level.java:6540) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:util.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:xycraft_core.mixin.json:LevelRainShieldMixin,pl:mixin:A}
    at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:util.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:xycraft_core.mixin.json:LevelRainShieldMixin,pl:mixin:A}
    at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23722!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix

-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
```

#### Suspected Mods:
- **Ars Nouveau**: The error originates in the `DungeonLootTables` class within this mod. This mod's loot generation logic seems to be passing an invalid bound to the random number generator.

#### Affected Block Entity:
- **Block Entity**: `botania:loonium` at location `(4126, 71, -15)` in the world. This suggests an interaction between the `Ars Nouveau` mod and the `Botania` mod, specifically the `Loonium` block entity.

#### Recommendations:
1. **Update Mods**: Ensure all mods, especially `Ars Nouveau` and `Botania`, are updated to their latest versions as updates often fix known bugs.
2. **Check Configurations**: Review the configuration files for `Ars Nouveau` to ensure no parameters are set to zero or negative values.
3. **Report to Mod Authors**: If updating and checking configurations do not resolve the issue, report the crash log to the developers of `Ars Nouveau` and `Botania`. They may provide a patch or further instructions to resolve the issue.

**Mod Versions:**
- Minecraft: 1.20.1
- Forge: 47.2.20
- Ars Nouveau: 4.11.0
- Botania: 1.20.1-444-FORGE

**System Details:**
- Operating System: Windows 10 (amd64)
- Java Version: 17.0.10
- Memory: 2152 MiB / 6240 MiB (up to 9936 MiB)
- CPU: AMD Ryzen 7 5800H with Radeon Graphics
- GPU: NVIDIA GeForce RTX 3050 Laptop GPU

**Steps to Reproduce:**
1. Place a `Botania Loonium` block in the world.
2. Allow the block to generate loot.
3. Observe the crash due to an invalid argument in the random number generation process.

Please address these issues to ensure a stable gameplay experience.

### Crash Log

https://gist.github.com/Alartias/4404377eaf90da4b97239d41e9918f5b

**Comment by phit** [comment]
until the mod issue is fixed, you can put this
[ritual_loot_blacklist.json](https://github.com/user-attachments/files/15742917/ritual_loot_blacklist.json)
into `kubejs/data/ars_nouveau/tags/items` 
your analysis is also slighty wrong, the issue is caused by the stream filter being inversed on line 66, right now this config is acting like a whitelist instead of a blacklist

**Comment by Alartias** [comment]
> until the mod issue is fixed, you can put this [ritual_loot_blacklist.json](https://github.com/user-attachments/files/15742917/ritual_loot_blacklist.json) into `kubejs/data/ars_nouveau/tags/items` your analysis is also slighty wrong, the issue is caused by the stream filter being inversed on line 66, right now this config is acting like a whitelist instead of a blacklist and there's no check if the resulting list has any items in it


This is an effective measure, and I've naturally been able to play normally. However, I'm curious as to why this small change hasn't been implemented in either of the two updates. Is there another reason for this?
