### ISSUE TITLE
[Crash]: NullPointerException : Cannot invoke "net.minecraft.world.level.chunk.DataLayer.m_62560_(int, int, int)" because "$$2" is null

### ISSUE THREAD

**Issue by LaplusIjns** [AllTheMods/All-the-mods-9-Sky#644]
### Possible Fixes

Yes

### Modpack Version

1.08~1.10

### What happened?

`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.chunk.DataLayer.m_62560_(int, int, int)" because "$$2" is null
	at net.minecraft.world.level.lighting.LayerLightSectionStorage.m_75795_(LayerLightSectionStorage.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.world.level.lighting.LightEngine.m_284361_(LightEngine.java:162) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.world.level.lighting.LightEngine.m_9323_(LightEngine.java:150) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(LevelLightEngine.java:53) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(ThreadedLevelLightEngine.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(ThreadedLevelLightEngine.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23685!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[018月2024 16:42:05.003] [spark-java-sampler-0-2/WARN] [spark/]: Timed out waiting for world statist`

even I try update latest version still occur NullPointerException 
There is also a reddit post have same problem  but no effective solution
https://www.reddit.com/r/allthemods/comments/1eg6fgo/server_not_starting_upon_after_update/

### Crash Log

https://gist.github.com/LaplusIjns/f995a23cdd84697262f6fe813c7ac78b#file-gistfile1-txt

**Comment by LaplusIjns** [comment]
Here are Chunks that cause crash
https://drive.google.com/file/d/1R73vHRXoohgeYUYNcIPyEh4HDBfmh3Tk/view?usp=sharing
position is about 12314 80 -4086
